version: '3'

services: 

    database:
        image: mongo
        ports: 
            - "27018:27017"
        volumes:
            - ./docker-data:/data/db

        
    backend:
        build: .
        ports: 
            - 9000:9000

        depends_on: 
            - database
        
